language: node_js
node_js: lts/*
branches:
  only:
    - master
script:
  - npm run lint
  - npm run build -- --prod
deploy:
  provider: firebase
  edge: true
  project: bellaenbasiel
  only: hosting
  token:
    secure: z6UBOoMvk+Sbp4luc7/9mhIx/n2igMlJFfIEqVaQEgovQRHWTrO3PWdCSurZ3ZdbKnovkmGQ9i/KEQurMgCbjT/YG/eq0DBr7+Ul/BNplF+8Lr3HivIHnZ83KhOSouKj3kCJPQh4B7c8njjmgVMy8r/YFpiExtCg72v8lL4BXSvkaDXiEOjvf4EXVdAq0qyqR9gt5+ExvVIAAWkz74OkyOCKYdx2LZzU6wF+EFCcB9kFCHmLe3ufzUZ017OJCbkxc1YrW4EIzGUhWZfRL5Gt3JtM7qbRYCWpTvPuejqWayHSNOKOa0+vIFAEhWOiC9qbNIzapLZJdtQOebLl4wqL9pdcM62E8O+trULUxA2wlGRCTTuxG7oh8nAxRHY2dY4THoiYYYHNzATkVCf7WLLGGLuIPBbVg9Lf02O1ukHDjF2GlyKAnpwJ6EmSotcqgjhdAuetOJKAU/QF9CEbOXjAsZSFubGwRIlEpJynDfwHYRC8TmFt2OCc0lgrOzSrcsyFUJWzhRWnzPk06tlvaYTY5LnFQN/emjURWIVs5djh3YVYPSRLmaTKUrSocTwaecKS90GhJ6Pq2wCu2mxQYrsvVUgwgrwIkFntHi7EGNq94ZA695iXo50Ldvl35h2UHRqqYG3y2DAzSBp3o6CUsyA8BTvDd9Ybkc7mE1bkry+eHoA=
